spring:
  application:
    name: ProjectAI
  datasource:
    url: jdbc:h2:mem:projectAI
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
      path: '/h2-console'

openai:
  base-url: https://api.openai.com
  api-key: ${OPENAI_API_KEY}
